<footer>

	<section class="footerBlock" id="infoSource">
		<h2>Information Sources</h2>
		<div>
			<a href="https://en.wikipedia.org/wiki/Global_warming#History">Wikipedia</a>
		</div>

		<div>
			<a href="https://www.nrdc.org/stories/how-you-can-stop-global-warming">How to Help</a>
		</div>

		<div>
			<a href="https://www.wwf.org.au/what-we-do/climate/causes-of-global-warming">wwf.org</a>
		</div>

		<div>
			<a href="https://www.nrdc.org/stories/how-you-can-stop-global-warming">nrdc.org</a>
		</div>

		<div>
			<a href="https://climate.nasa.gov/effects/">climate.nasa.gov</a>
		</div>
	</section>

	<section class="footerBlock" id="designSource">
		<h2>Design Sources</h2>
		<div>
			Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> 
			from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a> 
			is licensed by <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
		</div>
	</section>

	<section id="teamNames">
		<p>IA - Sharfuz Shifat, Designer - Kaleb Chitaphong, Coder - Reeshad Rahman</p>
	</section>

</footer>