<!DOCTYPE html>

<html lang="en">

	<head>
		<meta charset="UTF-8">
		<title>Global Warming</title>
        <link type="text/css" rel="stylesheet" href="css/style.css">

        <link type="text/css" rel="stylesheet" href="css/banner.css">
        <link type="text/css" rel="stylesheet" href="css/footer.css">

        <link href="https://fonts.googleapis.com/css?family=Lato|Poller+One" rel="stylesheet">
